# Generated by Django 3.0.6 on 2020-05-13 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('ingredients_text', models.TextField(blank=True)),
                ('allergens', models.TextField(blank=True)),
                ('serving_size', models.TextField(blank=True)),
                ('fat_100g', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
                ('cholesterol_100g', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
                ('carbohydrates_100g', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
                ('sugars_100g', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
                ('fiber_100g', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
                ('proteins_100g', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
                ('salt_100g', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
                ('sodium_100g', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
                ('alcohol_100g', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('h2_plasma_glucose', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8)),
                ('fasting_plasma_glucose', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8)),
                ('hbA1c', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
