# Generated by Django 3.0.1 on 2020-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_nutritionintake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionintake',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
