# Generated by Django 3.0.6 on 2020-05-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200518_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionintake',
            name='meal_type',
        ),
        migrations.AlterField(
            model_name='nutritionintake',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
