# Generated by Django 3.0.6 on 2020-05-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200522_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionintake',
            name='server_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
