# Generated by Django 3.0.6 on 2020-05-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200523_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionintake',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_item', to='dashboard.FoodItem'),
        ),
    ]
