# Generated by Django 3.0.6 on 2020-05-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200527_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='alcohol_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='carbohydrates_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fat_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fiber_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='proteins_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='salt_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='sodium_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='sugars_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
